name: Build and Deploy Spring Boot to AWS EC2

on: 
  push: 
    branches: [ "main" ]  

env:
  PROJECT_NAME: zooTopic
  BUCKET_NAME: tcat-spring
  CODE_DEPLOY_APP_NAME: RealLastZinMakFinal
  DEPLOYMENT_GROUP_NAME: RealLastZinMakFinal123

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle- 


      
      
 
      - name: Make application.yml
        run: |
          cd ./src/main
          cd ./resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml
        shell: bash
    

          

      - name: Grant execute permission for gradlew
        run: sudo chmod +x ./gradlew
        shell: bash
      
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash 
        
      - name: Make zip file
        run: |
          mkdir deploy
          cp ./appspec.yml ./deploy/
          cp ./Dockerfile ./deploy/
          cp ./scripts/*.sh ./deploy/
          cp ./build/libs/*.jar ./deploy/
          zip -r -qq -j ./spring-build.zip ./deploy



          
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      

      - name: Upload to S3
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            ./spring-build.zip s3://tcat-spring
            
      - name: Code Deploy
        run: aws deploy create-deployment --application-name RealLastZinMakFinal
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name RealLastZinMakFinal123
          --s3-location bucket=tcat-spring,bundleType=zip,key=spring-build.zip
      
     
